name: Matrix Build Go Binaries
on:
  workflow_call:
jobs:
  example:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { runner: ubuntu-latest, os: linux,   arch: amd64, env:  CGO_ENABLED=0, }
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build
        uses: hashicorp/actions-go-build@main
        with:
          product_name: go-rofi-bluetooth-menu
          product_version: 1.2.3
          go_version: 1.23
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          instructions: |-
            ${{ matrix.env }} \
              go build \
                -o "$BIN_PATH" \
                -trimpath \
                -buildvcs=true \
                "
      - name: Upload the built artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-rofi-bluetooth-menu
          path: "$BIN_PATH"
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "[${{ env.RELEASE_DATE }}]"
          files: |
            thesis_mclb.pdf

