name: Matrix Build Go Binaries
on:
  workflow_call:
jobs:
  build-go:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { name: go-rofi-bluetooth-menu, runner: ubuntu-latest, os: linux,   arch: amd64, env:  CGO_ENABLED=0 }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        env:
          NAME: "${{ matrix.name }}"
          GOOS: "${{ matrix.os }}"
          GOARCH: "${{ matrix.arch }}"
          CGO_ENABLED: "0"
        run: |
          go build \
            -trimpath \
            -buildvcs=true \
            -o dist/$PROJECT-$GOOS-$GOARCH
      - name: Upload the built artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-rofi-bluetooth-menu
          path: "dist/"
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
